name: PerformanceMonitor
version: ${pluginversion}
author: Narimm
main: me.mshax085.performanceMonitor.PerformanceMonitor

commands:
  serverstate:
    description: Show the server stats using a command
    usage: /serverstate
  ss:
    description: Short-Command for serverstate
    usage: /ss
    
permissions:
  pmonitor.showstate:
    description: Permission to show the server stats
    default: op